use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Phase {
    Solid,
    Liquid,
    Gas,
    Plasma,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Group {
    AlkaliMetal,
    AlkalineEarthMetal,
    TransitionMetal,
    PostTransitionMetal,
    Metalloid,
    ReactiveNonmetal,
    NobleGas,
    Lanthanide,
    Actinide,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Element {
    pub atomic_number: u8,
    pub symbol: &'static str,
    pub name: &'static str,
    pub atomic_mass: f64,       // unified atomic mass units
    pub group: Group,
    pub period: u8,
    pub melting_point_k: Option<f64>,
    pub boiling_point_k: Option<f64>,
    pub density_g_cm3: Option<f64>,
    pub electronegativity: Option<f64>, // Pauling scale
    pub abundance_crust_ppm: Option<f64>, // parts per million in Earth's crust
    pub abundance_universe_ppm: Option<f64>,
}

impl Element {
    pub fn phase_at(&self, temp_k: f64) -> Phase {
        match (self.melting_point_k, self.boiling_point_k) {
            (Some(mp), Some(bp)) => {
                if temp_k < mp { Phase::Solid }
                else if temp_k < bp { Phase::Liquid }
                else { Phase::Gas }
            }
            (Some(mp), None) => {
                if temp_k < mp { Phase::Solid } else { Phase::Gas }
            }
            _ => Phase::Gas,
        }
    }

    pub fn is_volatile(&self) -> bool {
        matches!(self.boiling_point_k, Some(bp) if bp < 400.0)
    }
}

/// Full periodic table — all 118 elements
pub fn periodic_table() -> Vec<Element> {
    vec![
        Element { atomic_number: 1,   symbol: "H",   name: "Hydrogen",      atomic_mass: 1.008,    group: Group::ReactiveNonmetal, period: 1, melting_point_k: Some(14.01),   boiling_point_k: Some(20.28),   density_g_cm3: Some(0.00009),  electronegativity: Some(2.20), abundance_crust_ppm: Some(1400.0),    abundance_universe_ppm: Some(739_000.0) },
        Element { atomic_number: 2,   symbol: "He",  name: "Helium",        atomic_mass: 4.003,    group: Group::NobleGas,         period: 1, melting_point_k: None,           boiling_point_k: Some(4.22),    density_g_cm3: Some(0.000164), electronegativity: None,        abundance_crust_ppm: Some(0.008),     abundance_universe_ppm: Some(240_000.0) },
        Element { atomic_number: 3,   symbol: "Li",  name: "Lithium",       atomic_mass: 6.941,    group: Group::AlkaliMetal,      period: 2, melting_point_k: Some(453.7),   boiling_point_k: Some(1615.0),  density_g_cm3: Some(0.534),    electronegativity: Some(0.98), abundance_crust_ppm: Some(20.0),      abundance_universe_ppm: Some(6.0) },
        Element { atomic_number: 4,   symbol: "Be",  name: "Beryllium",     atomic_mass: 9.012,    group: Group::AlkalineEarthMetal, period: 2, melting_point_k: Some(1560.0), boiling_point_k: Some(2742.0), density_g_cm3: Some(1.85),    electronegativity: Some(1.57), abundance_crust_ppm: Some(2.8),       abundance_universe_ppm: Some(0.1) },
        Element { atomic_number: 5,   symbol: "B",   name: "Boron",         atomic_mass: 10.81,    group: Group::Metalloid,        period: 2, melting_point_k: Some(2349.0),  boiling_point_k: Some(4200.0),  density_g_cm3: Some(2.34),     electronegativity: Some(2.04), abundance_crust_ppm: Some(10.0),      abundance_universe_ppm: Some(1.0) },
        Element { atomic_number: 6,   symbol: "C",   name: "Carbon",        atomic_mass: 12.011,   group: Group::ReactiveNonmetal, period: 2, melting_point_k: Some(3823.0),  boiling_point_k: Some(4300.0),  density_g_cm3: Some(2.267),    electronegativity: Some(2.55), abundance_crust_ppm: Some(200.0),     abundance_universe_ppm: Some(4600.0) },
        Element { atomic_number: 7,   symbol: "N",   name: "Nitrogen",      atomic_mass: 14.007,   group: Group::ReactiveNonmetal, period: 2, melting_point_k: Some(63.15),   boiling_point_k: Some(77.36),   density_g_cm3: Some(0.001251), electronegativity: Some(3.04), abundance_crust_ppm: Some(19.0),      abundance_universe_ppm: Some(960.0) },
        Element { atomic_number: 8,   symbol: "O",   name: "Oxygen",        atomic_mass: 15.999,   group: Group::ReactiveNonmetal, period: 2, melting_point_k: Some(54.36),   boiling_point_k: Some(90.20),   density_g_cm3: Some(0.001429), electronegativity: Some(3.44), abundance_crust_ppm: Some(461_000.0), abundance_universe_ppm: Some(10_400.0) },
        Element { atomic_number: 9,   symbol: "F",   name: "Fluorine",      atomic_mass: 18.998,   group: Group::ReactiveNonmetal, period: 2, melting_point_k: Some(53.53),   boiling_point_k: Some(85.03),   density_g_cm3: Some(0.001696), electronegativity: Some(3.98), abundance_crust_ppm: Some(585.0),     abundance_universe_ppm: Some(400.0) },
        Element { atomic_number: 10,  symbol: "Ne",  name: "Neon",          atomic_mass: 20.180,   group: Group::NobleGas,         period: 2, melting_point_k: Some(24.56),   boiling_point_k: Some(27.07),   density_g_cm3: Some(0.0009),   electronegativity: None,        abundance_crust_ppm: Some(0.007),     abundance_universe_ppm: Some(1340.0) },
        Element { atomic_number: 11,  symbol: "Na",  name: "Sodium",        atomic_mass: 22.990,   group: Group::AlkaliMetal,      period: 3, melting_point_k: Some(370.9),   boiling_point_k: Some(1156.0),  density_g_cm3: Some(0.968),    electronegativity: Some(0.93), abundance_crust_ppm: Some(23_600.0),  abundance_universe_ppm: Some(33.0) },
        Element { atomic_number: 12,  symbol: "Mg",  name: "Magnesium",     atomic_mass: 24.305,   group: Group::AlkalineEarthMetal, period: 3, melting_point_k: Some(923.0), boiling_point_k: Some(1363.0), density_g_cm3: Some(1.738),   electronegativity: Some(1.31), abundance_crust_ppm: Some(23_300.0),  abundance_universe_ppm: Some(580.0) },
        Element { atomic_number: 13,  symbol: "Al",  name: "Aluminum",      atomic_mass: 26.982,   group: Group::PostTransitionMetal, period: 3, melting_point_k: Some(933.5), boiling_point_k: Some(2792.0), density_g_cm3: Some(2.70),    electronegativity: Some(1.61), abundance_crust_ppm: Some(82_300.0),  abundance_universe_ppm: Some(58.0) },
        Element { atomic_number: 14,  symbol: "Si",  name: "Silicon",       atomic_mass: 28.086,   group: Group::Metalloid,        period: 3, melting_point_k: Some(1687.0),  boiling_point_k: Some(3538.0),  density_g_cm3: Some(2.329),    electronegativity: Some(1.90), abundance_crust_ppm: Some(282_000.0), abundance_universe_ppm: Some(724.0) },
        Element { atomic_number: 15,  symbol: "P",   name: "Phosphorus",    atomic_mass: 30.974,   group: Group::ReactiveNonmetal, period: 3, melting_point_k: Some(317.3),   boiling_point_k: Some(550.0),   density_g_cm3: Some(1.823),    electronegativity: Some(2.19), abundance_crust_ppm: Some(1050.0),    abundance_universe_ppm: Some(8.0) },
        Element { atomic_number: 16,  symbol: "S",   name: "Sulfur",        atomic_mass: 32.06,    group: Group::ReactiveNonmetal, period: 3, melting_point_k: Some(388.4),   boiling_point_k: Some(717.8),   density_g_cm3: Some(2.067),    electronegativity: Some(2.58), abundance_crust_ppm: Some(350.0),     abundance_universe_ppm: Some(444.0) },
        Element { atomic_number: 17,  symbol: "Cl",  name: "Chlorine",      atomic_mass: 35.45,    group: Group::ReactiveNonmetal, period: 3, melting_point_k: Some(171.6),   boiling_point_k: Some(239.1),   density_g_cm3: Some(0.003214), electronegativity: Some(3.16), abundance_crust_ppm: Some(145.0),     abundance_universe_ppm: Some(8.0) },
        Element { atomic_number: 18,  symbol: "Ar",  name: "Argon",         atomic_mass: 39.948,   group: Group::NobleGas,         period: 3, melting_point_k: Some(83.81),   boiling_point_k: Some(87.30),   density_g_cm3: Some(0.001784), electronegativity: None,        abundance_crust_ppm: Some(3.5),       abundance_universe_ppm: Some(133.0) },
        Element { atomic_number: 19,  symbol: "K",   name: "Potassium",     atomic_mass: 39.098,   group: Group::AlkaliMetal,      period: 4, melting_point_k: Some(336.5),   boiling_point_k: Some(1032.0),  density_g_cm3: Some(0.862),    electronegativity: Some(0.82), abundance_crust_ppm: Some(20_900.0),  abundance_universe_ppm: Some(3.7) },
        Element { atomic_number: 20,  symbol: "Ca",  name: "Calcium",       atomic_mass: 40.078,   group: Group::AlkalineEarthMetal, period: 4, melting_point_k: Some(1115.0), boiling_point_k: Some(1757.0), density_g_cm3: Some(1.55),    electronegativity: Some(1.00), abundance_crust_ppm: Some(41_500.0),  abundance_universe_ppm: Some(70.0) },
        Element { atomic_number: 21,  symbol: "Sc",  name: "Scandium",      atomic_mass: 44.956,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1814.0),  boiling_point_k: Some(3109.0),  density_g_cm3: Some(2.985),    electronegativity: Some(1.36), abundance_crust_ppm: Some(22.0),      abundance_universe_ppm: Some(0.12) },
        Element { atomic_number: 22,  symbol: "Ti",  name: "Titanium",      atomic_mass: 47.867,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1941.0),  boiling_point_k: Some(3560.0),  density_g_cm3: Some(4.506),    electronegativity: Some(1.54), abundance_crust_ppm: Some(5650.0),    abundance_universe_ppm: Some(3.0) },
        Element { atomic_number: 23,  symbol: "V",   name: "Vanadium",      atomic_mass: 50.942,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(2183.0),  boiling_point_k: Some(3680.0),  density_g_cm3: Some(6.11),     electronegativity: Some(1.63), abundance_crust_ppm: Some(120.0),     abundance_universe_ppm: Some(1.0) },
        Element { atomic_number: 24,  symbol: "Cr",  name: "Chromium",      atomic_mass: 51.996,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(2180.0),  boiling_point_k: Some(2944.0),  density_g_cm3: Some(7.15),     electronegativity: Some(1.66), abundance_crust_ppm: Some(102.0),     abundance_universe_ppm: Some(15.0) },
        Element { atomic_number: 25,  symbol: "Mn",  name: "Manganese",     atomic_mass: 54.938,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1519.0),  boiling_point_k: Some(2334.0),  density_g_cm3: Some(7.21),     electronegativity: Some(1.55), abundance_crust_ppm: Some(950.0),     abundance_universe_ppm: Some(10.0) },
        Element { atomic_number: 26,  symbol: "Fe",  name: "Iron",          atomic_mass: 55.845,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1811.0),  boiling_point_k: Some(3134.0),  density_g_cm3: Some(7.874),    electronegativity: Some(1.83), abundance_crust_ppm: Some(56_300.0),  abundance_universe_ppm: Some(1090.0) },
        Element { atomic_number: 27,  symbol: "Co",  name: "Cobalt",        atomic_mass: 58.933,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1768.0),  boiling_point_k: Some(3200.0),  density_g_cm3: Some(8.90),     electronegativity: Some(1.88), abundance_crust_ppm: Some(25.0),      abundance_universe_ppm: Some(4.0) },
        Element { atomic_number: 28,  symbol: "Ni",  name: "Nickel",        atomic_mass: 58.693,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1728.0),  boiling_point_k: Some(3186.0),  density_g_cm3: Some(8.908),    electronegativity: Some(1.91), abundance_crust_ppm: Some(84.0),      abundance_universe_ppm: Some(49.0) },
        Element { atomic_number: 29,  symbol: "Cu",  name: "Copper",        atomic_mass: 63.546,   group: Group::TransitionMetal,  period: 4, melting_point_k: Some(1357.8),  boiling_point_k: Some(2835.0),  density_g_cm3: Some(8.96),     electronegativity: Some(1.90), abundance_crust_ppm: Some(60.0),      abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 30,  symbol: "Zn",  name: "Zinc",          atomic_mass: 65.38,    group: Group::TransitionMetal,  period: 4, melting_point_k: Some(692.7),   boiling_point_k: Some(1180.0),  density_g_cm3: Some(7.133),    electronegativity: Some(1.65), abundance_crust_ppm: Some(70.0),      abundance_universe_ppm: Some(0.3) },
        Element { atomic_number: 31,  symbol: "Ga",  name: "Gallium",       atomic_mass: 69.723,   group: Group::PostTransitionMetal, period: 4, melting_point_k: Some(302.9), boiling_point_k: Some(2477.0), density_g_cm3: Some(5.91),    electronegativity: Some(1.81), abundance_crust_ppm: Some(19.0),      abundance_universe_ppm: Some(0.1) },
        Element { atomic_number: 32,  symbol: "Ge",  name: "Germanium",     atomic_mass: 72.630,   group: Group::Metalloid,        period: 4, melting_point_k: Some(1211.4),  boiling_point_k: Some(3106.0),  density_g_cm3: Some(5.323),    electronegativity: Some(2.01), abundance_crust_ppm: Some(1.5),       abundance_universe_ppm: Some(0.2) },
        Element { atomic_number: 33,  symbol: "As",  name: "Arsenic",       atomic_mass: 74.922,   group: Group::Metalloid,        period: 4, melting_point_k: Some(1090.0),  boiling_point_k: Some(887.0),   density_g_cm3: Some(5.727),    electronegativity: Some(2.18), abundance_crust_ppm: Some(1.8),       abundance_universe_ppm: Some(0.08) },
        Element { atomic_number: 34,  symbol: "Se",  name: "Selenium",      atomic_mass: 78.971,   group: Group::ReactiveNonmetal, period: 4, melting_point_k: Some(494.0),   boiling_point_k: Some(958.0),   density_g_cm3: Some(4.809),    electronegativity: Some(2.55), abundance_crust_ppm: Some(0.05),      abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 35,  symbol: "Br",  name: "Bromine",       atomic_mass: 79.904,   group: Group::ReactiveNonmetal, period: 4, melting_point_k: Some(265.8),   boiling_point_k: Some(332.0),   density_g_cm3: Some(3.103),    electronegativity: Some(2.96), abundance_crust_ppm: Some(2.4),       abundance_universe_ppm: Some(0.7) },
        Element { atomic_number: 36,  symbol: "Kr",  name: "Krypton",       atomic_mass: 83.798,   group: Group::NobleGas,         period: 4, melting_point_k: Some(115.8),   boiling_point_k: Some(119.9),   density_g_cm3: Some(0.003749), electronegativity: Some(3.00), abundance_crust_ppm: Some(0.0001),    abundance_universe_ppm: Some(0.55) },
        Element { atomic_number: 37,  symbol: "Rb",  name: "Rubidium",      atomic_mass: 85.468,   group: Group::AlkaliMetal,      period: 5, melting_point_k: Some(312.5),   boiling_point_k: Some(961.0),   density_g_cm3: Some(1.532),    electronegativity: Some(0.82), abundance_crust_ppm: Some(90.0),      abundance_universe_ppm: Some(0.7) },
        Element { atomic_number: 38,  symbol: "Sr",  name: "Strontium",     atomic_mass: 87.62,    group: Group::AlkalineEarthMetal, period: 5, melting_point_k: Some(1050.0), boiling_point_k: Some(1655.0), density_g_cm3: Some(2.64),    electronegativity: Some(0.95), abundance_crust_ppm: Some(370.0),     abundance_universe_ppm: Some(0.8) },
        Element { atomic_number: 39,  symbol: "Y",   name: "Yttrium",       atomic_mass: 88.906,   group: Group::TransitionMetal,  period: 5, melting_point_k: Some(1799.0),  boiling_point_k: Some(3609.0),  density_g_cm3: Some(4.472),    electronegativity: Some(1.22), abundance_crust_ppm: Some(33.0),      abundance_universe_ppm: Some(0.2) },
        Element { atomic_number: 40,  symbol: "Zr",  name: "Zirconium",     atomic_mass: 91.224,   group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2128.0),  boiling_point_k: Some(4682.0),  density_g_cm3: Some(6.52),     electronegativity: Some(1.33), abundance_crust_ppm: Some(165.0),     abundance_universe_ppm: Some(0.5) },
        Element { atomic_number: 41,  symbol: "Nb",  name: "Niobium",       atomic_mass: 92.906,   group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2750.0),  boiling_point_k: Some(5017.0),  density_g_cm3: Some(8.57),     electronegativity: Some(1.6),  abundance_crust_ppm: Some(20.0),      abundance_universe_ppm: Some(0.17) },
        Element { atomic_number: 42,  symbol: "Mo",  name: "Molybdenum",    atomic_mass: 95.95,    group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2896.0),  boiling_point_k: Some(4912.0),  density_g_cm3: Some(10.22),    electronegativity: Some(2.16), abundance_crust_ppm: Some(1.2),       abundance_universe_ppm: Some(0.9) },
        Element { atomic_number: 43,  symbol: "Tc",  name: "Technetium",    atomic_mass: 98.0,     group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2430.0),  boiling_point_k: Some(4538.0),  density_g_cm3: Some(11.0),     electronegativity: Some(1.9),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 44,  symbol: "Ru",  name: "Ruthenium",     atomic_mass: 101.07,   group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2607.0),  boiling_point_k: Some(4423.0),  density_g_cm3: Some(12.37),    electronegativity: Some(2.2),  abundance_crust_ppm: Some(0.001),     abundance_universe_ppm: Some(1.9) },
        Element { atomic_number: 45,  symbol: "Rh",  name: "Rhodium",       atomic_mass: 102.906,  group: Group::TransitionMetal,  period: 5, melting_point_k: Some(2237.0),  boiling_point_k: Some(3968.0),  density_g_cm3: Some(12.41),    electronegativity: Some(2.28), abundance_crust_ppm: Some(0.001),     abundance_universe_ppm: Some(0.4) },
        Element { atomic_number: 46,  symbol: "Pd",  name: "Palladium",     atomic_mass: 106.42,   group: Group::TransitionMetal,  period: 5, melting_point_k: Some(1828.1),  boiling_point_k: Some(3236.0),  density_g_cm3: Some(12.023),   electronegativity: Some(2.20), abundance_crust_ppm: Some(0.015),     abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 47,  symbol: "Ag",  name: "Silver",        atomic_mass: 107.868,  group: Group::TransitionMetal,  period: 5, melting_point_k: Some(1234.9),  boiling_point_k: Some(2435.0),  density_g_cm3: Some(10.49),    electronegativity: Some(1.93), abundance_crust_ppm: Some(0.075),     abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 48,  symbol: "Cd",  name: "Cadmium",       atomic_mass: 112.414,  group: Group::TransitionMetal,  period: 5, melting_point_k: Some(594.2),   boiling_point_k: Some(1040.0),  density_g_cm3: Some(8.65),     electronegativity: Some(1.69), abundance_crust_ppm: Some(0.15),      abundance_universe_ppm: Some(0.2) },
        Element { atomic_number: 49,  symbol: "In",  name: "Indium",        atomic_mass: 114.818,  group: Group::PostTransitionMetal, period: 5, melting_point_k: Some(429.7), boiling_point_k: Some(2345.0), density_g_cm3: Some(7.31),    electronegativity: Some(1.78), abundance_crust_ppm: Some(0.25),      abundance_universe_ppm: Some(0.1) },
        Element { atomic_number: 50,  symbol: "Sn",  name: "Tin",           atomic_mass: 118.710,  group: Group::PostTransitionMetal, period: 5, melting_point_k: Some(505.1), boiling_point_k: Some(2875.0), density_g_cm3: Some(7.287),   electronegativity: Some(1.96), abundance_crust_ppm: Some(2.3),       abundance_universe_ppm: Some(0.4) },
        Element { atomic_number: 51,  symbol: "Sb",  name: "Antimony",      atomic_mass: 121.760,  group: Group::Metalloid,        period: 5, melting_point_k: Some(903.8),   boiling_point_k: Some(1860.0),  density_g_cm3: Some(6.697),    electronegativity: Some(2.05), abundance_crust_ppm: Some(0.2),       abundance_universe_ppm: Some(0.15) },
        Element { atomic_number: 52,  symbol: "Te",  name: "Tellurium",     atomic_mass: 127.60,   group: Group::Metalloid,        period: 5, melting_point_k: Some(722.7),   boiling_point_k: Some(1261.0),  density_g_cm3: Some(6.24),     electronegativity: Some(2.10), abundance_crust_ppm: Some(0.001),     abundance_universe_ppm: Some(2.5) },
        Element { atomic_number: 53,  symbol: "I",   name: "Iodine",        atomic_mass: 126.904,  group: Group::ReactiveNonmetal, period: 5, melting_point_k: Some(386.9),   boiling_point_k: Some(457.4),   density_g_cm3: Some(4.933),    electronegativity: Some(2.66), abundance_crust_ppm: Some(0.45),      abundance_universe_ppm: Some(0.9) },
        Element { atomic_number: 54,  symbol: "Xe",  name: "Xenon",         atomic_mass: 131.293,  group: Group::NobleGas,         period: 5, melting_point_k: Some(161.4),   boiling_point_k: Some(165.1),   density_g_cm3: Some(0.005887), electronegativity: Some(2.60), abundance_crust_ppm: Some(0.00003),   abundance_universe_ppm: Some(1.7) },
        Element { atomic_number: 55,  symbol: "Cs",  name: "Cesium",        atomic_mass: 132.905,  group: Group::AlkaliMetal,      period: 6, melting_point_k: Some(301.6),   boiling_point_k: Some(944.0),   density_g_cm3: Some(1.873),    electronegativity: Some(0.79), abundance_crust_ppm: Some(3.0),       abundance_universe_ppm: Some(0.08) },
        Element { atomic_number: 56,  symbol: "Ba",  name: "Barium",        atomic_mass: 137.327,  group: Group::AlkalineEarthMetal, period: 6, melting_point_k: Some(1000.0), boiling_point_k: Some(2118.0), density_g_cm3: Some(3.594),   electronegativity: Some(0.89), abundance_crust_ppm: Some(425.0),     abundance_universe_ppm: Some(1.6) },
        Element { atomic_number: 57,  symbol: "La",  name: "Lanthanum",     atomic_mass: 138.905,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1193.0),  boiling_point_k: Some(3737.0),  density_g_cm3: Some(6.162),    electronegativity: Some(1.10), abundance_crust_ppm: Some(39.0),      abundance_universe_ppm: Some(0.2) },
        Element { atomic_number: 58,  symbol: "Ce",  name: "Cerium",        atomic_mass: 140.116,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1068.0),  boiling_point_k: Some(3716.0),  density_g_cm3: Some(6.770),    electronegativity: Some(1.12), abundance_crust_ppm: Some(66.5),      abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 59,  symbol: "Pr",  name: "Praseodymium",  atomic_mass: 140.908,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1208.0),  boiling_point_k: Some(3793.0),  density_g_cm3: Some(6.77),     electronegativity: Some(1.13), abundance_crust_ppm: Some(9.2),       abundance_universe_ppm: Some(0.09) },
        Element { atomic_number: 60,  symbol: "Nd",  name: "Neodymium",     atomic_mass: 144.242,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1297.0),  boiling_point_k: Some(3347.0),  density_g_cm3: Some(7.01),     electronegativity: Some(1.14), abundance_crust_ppm: Some(41.5),      abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 61,  symbol: "Pm",  name: "Promethium",    atomic_mass: 145.0,    group: Group::Lanthanide,       period: 6, melting_point_k: Some(1315.0),  boiling_point_k: Some(3273.0),  density_g_cm3: Some(7.26),     electronegativity: Some(1.13), abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 62,  symbol: "Sm",  name: "Samarium",      atomic_mass: 150.36,   group: Group::Lanthanide,       period: 6, melting_point_k: Some(1345.0),  boiling_point_k: Some(2067.0),  density_g_cm3: Some(7.52),     electronegativity: Some(1.17), abundance_crust_ppm: Some(7.05),      abundance_universe_ppm: Some(0.3) },
        Element { atomic_number: 63,  symbol: "Eu",  name: "Europium",      atomic_mass: 151.964,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1099.0),  boiling_point_k: Some(1802.0),  density_g_cm3: Some(5.244),    electronegativity: Some(1.2),  abundance_crust_ppm: Some(2.0),       abundance_universe_ppm: Some(0.05) },
        Element { atomic_number: 64,  symbol: "Gd",  name: "Gadolinium",    atomic_mass: 157.25,   group: Group::Lanthanide,       period: 6, melting_point_k: Some(1585.0),  boiling_point_k: Some(3546.0),  density_g_cm3: Some(7.90),     electronegativity: Some(1.20), abundance_crust_ppm: Some(6.2),       abundance_universe_ppm: Some(0.4) },
        Element { atomic_number: 65,  symbol: "Tb",  name: "Terbium",       atomic_mass: 158.925,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1629.0),  boiling_point_k: Some(3503.0),  density_g_cm3: Some(8.229),    electronegativity: Some(1.10), abundance_crust_ppm: Some(1.2),       abundance_universe_ppm: Some(0.06) },
        Element { atomic_number: 66,  symbol: "Dy",  name: "Dysprosium",    atomic_mass: 162.500,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1680.0),  boiling_point_k: Some(2840.0),  density_g_cm3: Some(8.551),    electronegativity: Some(1.22), abundance_crust_ppm: Some(5.2),       abundance_universe_ppm: Some(0.4) },
        Element { atomic_number: 67,  symbol: "Ho",  name: "Holmium",       atomic_mass: 164.930,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1734.0),  boiling_point_k: Some(2993.0),  density_g_cm3: Some(8.795),    electronegativity: Some(1.23), abundance_crust_ppm: Some(1.3),       abundance_universe_ppm: Some(0.1) },
        Element { atomic_number: 68,  symbol: "Er",  name: "Erbium",        atomic_mass: 167.259,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1802.0),  boiling_point_k: Some(3141.0),  density_g_cm3: Some(9.066),    electronegativity: Some(1.24), abundance_crust_ppm: Some(3.5),       abundance_universe_ppm: Some(0.3) },
        Element { atomic_number: 69,  symbol: "Tm",  name: "Thulium",       atomic_mass: 168.934,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1818.0),  boiling_point_k: Some(2223.0),  density_g_cm3: Some(9.321),    electronegativity: Some(1.25), abundance_crust_ppm: Some(0.52),      abundance_universe_ppm: Some(0.05) },
        Element { atomic_number: 70,  symbol: "Yb",  name: "Ytterbium",     atomic_mass: 173.045,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1097.0),  boiling_point_k: Some(1469.0),  density_g_cm3: Some(6.965),    electronegativity: Some(1.10), abundance_crust_ppm: Some(3.2),       abundance_universe_ppm: Some(0.3) },
        Element { atomic_number: 71,  symbol: "Lu",  name: "Lutetium",      atomic_mass: 174.967,  group: Group::Lanthanide,       period: 6, melting_point_k: Some(1925.0),  boiling_point_k: Some(3675.0),  density_g_cm3: Some(9.841),    electronegativity: Some(1.27), abundance_crust_ppm: Some(0.8),       abundance_universe_ppm: Some(0.07) },
        Element { atomic_number: 72,  symbol: "Hf",  name: "Hafnium",       atomic_mass: 178.49,   group: Group::TransitionMetal,  period: 6, melting_point_k: Some(2506.0),  boiling_point_k: Some(4876.0),  density_g_cm3: Some(13.31),    electronegativity: Some(1.3),  abundance_crust_ppm: Some(3.0),       abundance_universe_ppm: Some(0.17) },
        Element { atomic_number: 73,  symbol: "Ta",  name: "Tantalum",      atomic_mass: 180.948,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(3290.0),  boiling_point_k: Some(5731.0),  density_g_cm3: Some(16.65),    electronegativity: Some(1.5),  abundance_crust_ppm: Some(2.0),       abundance_universe_ppm: Some(0.02) },
        Element { atomic_number: 74,  symbol: "W",   name: "Tungsten",      atomic_mass: 183.84,   group: Group::TransitionMetal,  period: 6, melting_point_k: Some(3695.0),  boiling_point_k: Some(5828.0),  density_g_cm3: Some(19.25),    electronegativity: Some(2.36), abundance_crust_ppm: Some(1.25),      abundance_universe_ppm: Some(0.16) },
        Element { atomic_number: 75,  symbol: "Re",  name: "Rhenium",       atomic_mass: 186.207,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(3459.0),  boiling_point_k: Some(5869.0),  density_g_cm3: Some(21.02),    electronegativity: Some(1.9),  abundance_crust_ppm: Some(0.0007),    abundance_universe_ppm: Some(0.05) },
        Element { atomic_number: 76,  symbol: "Os",  name: "Osmium",        atomic_mass: 190.23,   group: Group::TransitionMetal,  period: 6, melting_point_k: Some(3306.0),  boiling_point_k: Some(5285.0),  density_g_cm3: Some(22.59),    electronegativity: Some(2.2),  abundance_crust_ppm: Some(0.0015),    abundance_universe_ppm: Some(0.9) },
        Element { atomic_number: 77,  symbol: "Ir",  name: "Iridium",       atomic_mass: 192.217,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(2719.0),  boiling_point_k: Some(4403.0),  density_g_cm3: Some(22.56),    electronegativity: Some(2.20), abundance_crust_ppm: Some(0.001),     abundance_universe_ppm: Some(1.0) },
        Element { atomic_number: 78,  symbol: "Pt",  name: "Platinum",      atomic_mass: 195.084,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(2041.4),  boiling_point_k: Some(4098.0),  density_g_cm3: Some(21.45),    electronegativity: Some(2.28), abundance_crust_ppm: Some(0.005),     abundance_universe_ppm: Some(1.7) },
        Element { atomic_number: 79,  symbol: "Au",  name: "Gold",          atomic_mass: 196.967,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(1337.3),  boiling_point_k: Some(3129.0),  density_g_cm3: Some(19.30),    electronegativity: Some(2.54), abundance_crust_ppm: Some(0.004),     abundance_universe_ppm: Some(0.6) },
        Element { atomic_number: 80,  symbol: "Hg",  name: "Mercury",       atomic_mass: 200.592,  group: Group::TransitionMetal,  period: 6, melting_point_k: Some(234.3),   boiling_point_k: Some(629.9),   density_g_cm3: Some(13.534),   electronegativity: Some(2.00), abundance_crust_ppm: Some(0.085),     abundance_universe_ppm: Some(0.4) },
        Element { atomic_number: 81,  symbol: "Tl",  name: "Thallium",      atomic_mass: 204.38,   group: Group::PostTransitionMetal, period: 6, melting_point_k: Some(577.0), boiling_point_k: Some(1746.0), density_g_cm3: Some(11.85),   electronegativity: Some(1.62), abundance_crust_ppm: Some(0.85),      abundance_universe_ppm: Some(0.1) },
        Element { atomic_number: 82,  symbol: "Pb",  name: "Lead",          atomic_mass: 207.2,    group: Group::PostTransitionMetal, period: 6, melting_point_k: Some(600.6), boiling_point_k: Some(2022.0), density_g_cm3: Some(11.34),   electronegativity: Some(2.33), abundance_crust_ppm: Some(14.0),      abundance_universe_ppm: Some(1.4) },
        Element { atomic_number: 83,  symbol: "Bi",  name: "Bismuth",       atomic_mass: 208.980,  group: Group::PostTransitionMetal, period: 6, melting_point_k: Some(544.6), boiling_point_k: Some(1837.0), density_g_cm3: Some(9.787),   electronegativity: Some(2.02), abundance_crust_ppm: Some(0.009),     abundance_universe_ppm: Some(0.7) },
        Element { atomic_number: 84,  symbol: "Po",  name: "Polonium",      atomic_mass: 209.0,    group: Group::PostTransitionMetal, period: 6, melting_point_k: Some(527.0), boiling_point_k: Some(1235.0), density_g_cm3: Some(9.196),   electronegativity: Some(2.0),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 85,  symbol: "At",  name: "Astatine",      atomic_mass: 210.0,    group: Group::ReactiveNonmetal, period: 6, melting_point_k: Some(575.0),   boiling_point_k: Some(610.0),   density_g_cm3: Some(7.0),      electronegativity: Some(2.2),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 86,  symbol: "Rn",  name: "Radon",         atomic_mass: 222.0,    group: Group::NobleGas,         period: 6, melting_point_k: Some(202.0),   boiling_point_k: Some(211.5),   density_g_cm3: Some(0.00973),  electronegativity: Some(2.2),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 87,  symbol: "Fr",  name: "Francium",      atomic_mass: 223.0,    group: Group::AlkaliMetal,      period: 7, melting_point_k: Some(300.0),   boiling_point_k: Some(950.0),   density_g_cm3: Some(1.87),     electronegativity: Some(0.7),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 88,  symbol: "Ra",  name: "Radium",        atomic_mass: 226.0,    group: Group::AlkalineEarthMetal, period: 7, melting_point_k: Some(973.0), boiling_point_k: Some(1413.0), density_g_cm3: Some(5.0),     electronegativity: Some(0.9),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 89,  symbol: "Ac",  name: "Actinium",      atomic_mass: 227.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1323.0),  boiling_point_k: Some(3471.0),  density_g_cm3: Some(10.07),    electronegativity: Some(1.1),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 90,  symbol: "Th",  name: "Thorium",       atomic_mass: 232.038,  group: Group::Actinide,         period: 7, melting_point_k: Some(2023.0),  boiling_point_k: Some(5061.0),  density_g_cm3: Some(11.72),    electronegativity: Some(1.3),  abundance_crust_ppm: Some(9.6),       abundance_universe_ppm: Some(0.13) },
        Element { atomic_number: 91,  symbol: "Pa",  name: "Protactinium",  atomic_mass: 231.036,  group: Group::Actinide,         period: 7, melting_point_k: Some(1841.0),  boiling_point_k: Some(4300.0),  density_g_cm3: Some(15.37),    electronegativity: Some(1.5),  abundance_crust_ppm: Some(0.0014),    abundance_universe_ppm: None },
        Element { atomic_number: 92,  symbol: "U",   name: "Uranium",       atomic_mass: 238.029,  group: Group::Actinide,         period: 7, melting_point_k: Some(1405.3),  boiling_point_k: Some(4404.0),  density_g_cm3: Some(19.05),    electronegativity: Some(1.38), abundance_crust_ppm: Some(2.7),       abundance_universe_ppm: Some(0.026) },
        Element { atomic_number: 93,  symbol: "Np",  name: "Neptunium",     atomic_mass: 237.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(912.0),   boiling_point_k: Some(4175.0),  density_g_cm3: Some(20.45),    electronegativity: Some(1.36), abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 94,  symbol: "Pu",  name: "Plutonium",     atomic_mass: 244.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(912.5),   boiling_point_k: Some(3501.0),  density_g_cm3: Some(19.816),   electronegativity: Some(1.28), abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 95,  symbol: "Am",  name: "Americium",     atomic_mass: 243.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1449.0),  boiling_point_k: Some(2880.0),  density_g_cm3: Some(13.69),    electronegativity: Some(1.13), abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 96,  symbol: "Cm",  name: "Curium",        atomic_mass: 247.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1613.0),  boiling_point_k: Some(3383.0),  density_g_cm3: Some(13.51),    electronegativity: Some(1.28), abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 97,  symbol: "Bk",  name: "Berkelium",     atomic_mass: 247.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1259.0),  boiling_point_k: None,          density_g_cm3: Some(14.78),    electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 98,  symbol: "Cf",  name: "Californium",   atomic_mass: 251.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1173.0),  boiling_point_k: None,          density_g_cm3: Some(15.1),     electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 99,  symbol: "Es",  name: "Einsteinium",   atomic_mass: 252.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1133.0),  boiling_point_k: None,          density_g_cm3: Some(8.84),     electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 100, symbol: "Fm",  name: "Fermium",       atomic_mass: 257.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1800.0),  boiling_point_k: None,          density_g_cm3: None,           electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 101, symbol: "Md",  name: "Mendelevium",   atomic_mass: 258.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1100.0),  boiling_point_k: None,          density_g_cm3: None,           electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 102, symbol: "No",  name: "Nobelium",      atomic_mass: 259.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1100.0),  boiling_point_k: None,          density_g_cm3: None,           electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 103, symbol: "Lr",  name: "Lawrencium",    atomic_mass: 266.0,    group: Group::Actinide,         period: 7, melting_point_k: Some(1900.0),  boiling_point_k: None,          density_g_cm3: None,           electronegativity: Some(1.3),  abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 104, symbol: "Rf",  name: "Rutherfordium", atomic_mass: 267.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: Some(2400.0),  boiling_point_k: Some(5800.0),  density_g_cm3: Some(23.2),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 105, symbol: "Db",  name: "Dubnium",       atomic_mass: 268.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(29.3),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 106, symbol: "Sg",  name: "Seaborgium",    atomic_mass: 269.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(35.0),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 107, symbol: "Bh",  name: "Bohrium",       atomic_mass: 270.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(37.1),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 108, symbol: "Hs",  name: "Hassium",       atomic_mass: 277.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(40.7),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 109, symbol: "Mt",  name: "Meitnerium",    atomic_mass: 278.0,    group: Group::Unknown,          period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(37.4),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 110, symbol: "Ds",  name: "Darmstadtium",  atomic_mass: 281.0,    group: Group::Unknown,          period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(34.8),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 111, symbol: "Rg",  name: "Roentgenium",   atomic_mass: 282.0,    group: Group::Unknown,          period: 7, melting_point_k: None,          boiling_point_k: None,          density_g_cm3: Some(28.7),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 112, symbol: "Cn",  name: "Copernicium",   atomic_mass: 285.0,    group: Group::TransitionMetal,  period: 7, melting_point_k: None,          boiling_point_k: Some(357.0),   density_g_cm3: Some(14.0),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 113, symbol: "Nh",  name: "Nihonium",      atomic_mass: 286.0,    group: Group::PostTransitionMetal, period: 7, melting_point_k: Some(700.0), boiling_point_k: Some(1430.0), density_g_cm3: Some(16.0),    electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 114, symbol: "Fl",  name: "Flerovium",     atomic_mass: 289.0,    group: Group::PostTransitionMetal, period: 7, melting_point_k: Some(284.0), boiling_point_k: Some(420.0),  density_g_cm3: Some(14.0),    electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 115, symbol: "Mc",  name: "Moscovium",     atomic_mass: 290.0,    group: Group::PostTransitionMetal, period: 7, melting_point_k: Some(670.0), boiling_point_k: Some(1400.0), density_g_cm3: Some(13.5),    electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 116, symbol: "Lv",  name: "Livermorium",   atomic_mass: 293.0,    group: Group::PostTransitionMetal, period: 7, melting_point_k: Some(637.0), boiling_point_k: Some(1085.0), density_g_cm3: Some(12.9),    electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 117, symbol: "Ts",  name: "Tennessine",    atomic_mass: 294.0,    group: Group::ReactiveNonmetal, period: 7, melting_point_k: Some(623.0),   boiling_point_k: Some(883.0),   density_g_cm3: Some(7.17),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
        Element { atomic_number: 118, symbol: "Og",  name: "Oganesson",     atomic_mass: 294.0,    group: Group::NobleGas,         period: 7, melting_point_k: Some(325.0),   boiling_point_k: Some(450.0),   density_g_cm3: Some(4.95),     electronegativity: None,        abundance_crust_ppm: None,            abundance_universe_ppm: None },
    ]
}

pub fn element_by_number(n: u8) -> Option<Element> {
    periodic_table().into_iter().find(|e| e.atomic_number == n)
}

pub fn element_by_symbol(sym: &str) -> Option<Element> {
    periodic_table().into_iter().find(|e| e.symbol == sym)
}
